version: '3.8'

services:
  mysql-server:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    networks:
      - system-default
    restart: unless-stopped

  web:
    build: ./project
    ports:
      - 8000:8000
    command: python3 run.py
    volumes:
      - ./workspace:/usr/src/app/workspace
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=db+mysql+pymysql://root:admin@mysql-server:3306/task
    depends_on:
      - redis
      - mysql-server
    networks:
      - system-default

  default:
    build: ./project
    command: celery -A worker.celery worker -c 1 --loglevel=info --prefetch-multiplier 10 -Q default
    volumes:
      - ./workspace:/usr/src/app/workspace
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=db+mysql+pymysql://root:admin@mysql-server:3306/task
    depends_on:
      - web
      - redis
    networks:
      - system-default

  highpriority:
    build: ./project
    command: celery -A worker.celery worker -c 10 --loglevel=info -Q priority_high
    volumes:
      - ./workspace:/usr/src/app/workspace
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=db+mysql+pymysql://root:admin@mysql-server:3306/task
    depends_on:
      - web
      - redis
    networks:
      - system-default

  redis:
    image: redis:6-alpine
    volumes:
      - /usr/local/etc/redis:/usr/local/etc/redis
    networks:
      - system-default
    restart: unless-stopped

  # redis:
  #   image: redis:6-alpine
  #   networks:
  #     - system-default

  dashboard:
    build: ./project
    command: celery flower -A worker.celery --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=db+mysql+pymysql://root:toolkitsecret@mysql-server:3306/task
    depends_on:
      - web
      - redis
      - default
      - highpriority
    networks:
      - system-default

networks:
  system-default:
    name: system-default
